### ISSUE TITLE
home: hero image text + carousel

### ISSUE THREAD

**Issue by GVFTW** [drawby/shopify-issues#40]
- Carousel and buttons buttons not working
- Move carousel dots to correct place
- Style Text to PSD and move to correct place. Width should be at 1/3 of the grid and extend to the edge

<img width="1098" alt="screen shot 2016-02-19 at 12 15 40 am" src="https://cloud.githubusercontent.com/assets/3649059/13195828/95e9700e-d789-11e5-87fd-e4b4c3805d90.png">

**Comment by EmilioTelevision** [comment]
fixed

**Comment by GVFTW** [comment]
carousel still doesn't function
dots still not in right place. refer to screenshot above.

**Comment by EmilioTelevision** [comment]
all working 
![image](https://cloud.githubusercontent.com/assets/3394886/13325583/6e7cfe2a-dbb0-11e5-8b6a-f5e242ada3f8.png)

**Comment by GVFTW** [comment]
let's slide dots up a few px so its flush with button's lower border
<img width="457" alt="screen shot 2016-02-25 at 12 30 14 pm" src="https://cloud.githubusercontent.com/assets/3649059/13328892/3cab15d0-dbbf-11e5-9567-80f474447046.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/13417186/4c3094a0-df37-11e5-8fe3-4b9ba9ca1f85.png)
